<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>probe</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../Vellichor.Dat/Vellichor.Dat.csproj" />
  </ItemGroup>
</Project>
